services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ecommerce
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql

  valkey:
    image: valkey/valkey:9.1.2
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    command: ["valkey-server", "--appendonly", "yes"]
    volumes:
      - valkey_data:/data

volumes:
  db_data:
  valkey_data: